import { LINE, PIE, BAR, SCATTER, RADAR, GRAPH } from './types';
import { ZOOM_IN, ZOOM_OUT, DOWNLOAD_IMAGE } from './buttonTypes';

export const BUTTONS_DEFAULTS_SET = {
  [LINE]: [ZOOM_IN, ZOOM_OUT, DOWNLOAD_IMAGE],
  [BAR]: [ZOOM_IN, ZOOM_OUT, DOWNLOAD_IMAGE],
  [PIE]: [DOWNLOAD_IMAGE],
  [SCATTER]: [ZOOM_IN, ZOOM_OUT, DOWNLOAD_IMAGE],
  [RADAR]: [DOWNLOAD_IMAGE],
  [GRAPH]: [DOWNLOAD_IMAGE],
};
